Update bindings.md
uber/h3 pull request #754
Opened 2023-02-17 19:25 UTC by hui-zheng

Added the recently h3 implementation by Databricks. https://www.databricks.com/blog/2023/01/12/supercharging-h3-geospatial-analytics.html

2023-02-17 19:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/uber/h3?pullRequest=754) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/uber/h3?pullRequest=754) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/uber/h3?pullRequest=754) it.</sub>

2023-02-17 20:06 UTC, dfellis approved these changes

2023-02-17 20:20 UTC, nrabinowitz approved these changes
Thanks for contributing!

2023-02-18 01:13 UTC, ajfriend commented
I think "Databrick" should be plural here.

2023-02-18 01:14 UTC, ajfriend requested changes
Databrick(s) should be plural, I believe

2023-02-24 01:00 UTC, dfellis commented on website/docs/community/bindings.md
> +## Databrick
```suggestion
## Databricks
```

2023-02-24 16:11 UTC, dfellis approved these changes

2023-02-24 18:43 UTC, ajfriend approved these changes

2023-02-24 18:43 UTC, merged